[features]
seeds = false
[programs.testnet]
my_solana_program = "532TetZomjgv4YZEjEeLEk6GweyzCvXRTb7o1t2RKqMe"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "testnet"
wallet = "/home/benz/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
